### ISSUE TITLE
[New API] : Wrapper for Storing and Retrieving MultiMedia Files via AWS S3 & Cloudfront.

### ISSUE THREAD

**Issue by zakhaev26** [developer-student-clubs/APIVerse#28]
### Brief Description 🤓

- This is a Wrapper API which helps to upload images/video or any type of Multimedia Files to AWS S3 Bucket and Retrieve them Back using AWS Cloudfront.
- This would help in increasing Scalability,Cost Efficiency,Performance and Reducing Database Loads,Providing easy to call API's to Get and Store objects.

### How will you develop it?🤩

- Tech Stack : NodeJS as the Runtime, ExpressJS , MongoDB/Postgres for referencing the hashes for later, Amazon Web Services
- User just needs to Configure some things for creating the Buckets [Documentation will be attached with it.]

### Deployment

Yes

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @zakhaev26🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Any updates @zakhaev26?

**Comment by zakhaev26** [comment]
Yeah.I am working on the API. Will make a PR by today.
Sorry for the delay.

**Comment by dishamodi0910** [comment]
Hey @zakhaev26 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
