### ISSUE TITLE
[API Enhancement] : Replace var with const for Better Code Efficiency

### ISSUE THREAD

**Issue by Vibgitcode27** [developer-student-clubs/APIVerse#37]
### Brief Description 🤓

# Title:

**Replace `var` with `const` for Better Code Efficiency**

### Issue:

I've observed that in 
> New_APIs/Demo_CRUD_API'/src/index.js

 within this repository, we're using the `var` keyword for variable declarations. The usage of `var` can lead to potential hoisting and scope-related issues. With ES6 and beyond, we have better ways to declare variables using `let` and `const`.

### Suggestion:

Wherever possible and applicable, it would be more efficient to use `const` (for variables that don't change their value) and `let` (for variables that do). This would not only make our code more modern but also more predictable in terms of variable scope and lifecycle.

### Benefits:

-   **Immutability**: By using `const`, we can ensure that the value of a variable doesn't change unexpectedly.
-   **Block Scope**: Both `let` and `const` are block-scoped, which reduces the risk of unintended side effects.
-   **Readability**: Modern JS practices are becoming standard, and using `const` and `let` increases the codebase's readability.

## 📌 Request for Assignment:

-   **I'd like to work on this issue.** Please assign it to me.

### Select the open source program you are contributing to

hacktoberfest-23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Vibgitcode27🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Vibgitcode27 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
