### ISSUE TITLE
[New API] : Movie And Tv Show

### ISSUE THREAD

**Issue by thesohailjafri** [developer-student-clubs/APIVerse#40]
### Brief Description 🤓

Rest API to fetch data of movie and tv-show with filter options of page, limit, search, and type

### How will you develop it?🤩

Node.js and Express.js

### Deployment

No

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Hey @thesohailjafri ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
