### ISSUE TITLE
[New API] : Creating API using Json-server and testing in Angular application

### ISSUE THREAD

**Issue by kunjgit** [developer-student-clubs/APIVerse#47]
### Brief Description 🤓

I want to build an API which will take one json any json file containing any kind of data inside that and it will give you the API with all the request methods for all of those object you specify in the datasource file and will give you the interface to interact with it and perform all types of requests 🚀 
I will test it with Angular application by having dependency injection of that API and calling that as well !

Hoping for some good contribution in API Verse 😃 !

### How will you develop it?🤩

I have just created a simple API using json-server entity and I am testing that using dependency injection in Angular by using some services !
You can have all kind of request through the API !
The way to create an API is pretty simple by using npm module json-server 😃 

### Deployment

No

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @kunjgit🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @kunjgit ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
