### ISSUE TITLE
[Existing API Name] : QR Generator API

### ISSUE THREAD

**Issue by dhruvishavaghani** [developer-student-clubs/APIVerse#6]
### Brief Description 🤓

QR code generator API is used to create QR code for any given URL.
QR Code is very efficient way of sharing various types of data among various users without sharing url with them. OQ Code makes it simpler by providing the functionality of simply scanning and accessing.

### Provide reference!

Referenced From: API Ninja
https://api-ninjas.com/api/qrcode

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @dhruvishavaghani🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @dhruvishavaghani ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
